#!/usr/bin/env sh

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
chown sail:www-data -R /var/www/html/storage

if [ $# -gt 0 ];then
    exec su-exec sail "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
